### ISSUE TITLE
Incorrect Hsv -> LinSrgb conversion on arm architecture (Raspberry Pi 1)

### ISSUE THREAD

**Issue by tiziano88** [Ogeon/palette#109] opened 2018-06-27 23:03 UTC
This may require more instructions on how to reproduce, but here is the main issue:

```rust
fn main() {
    let hsv = palette::Hsv::new(palette::RgbHue::<f32>::from_degrees(284.0), 1.0, 0.5);
    println!("HSV: {:?}", hsv);
    let rgb: palette::rgb::LinSrgb = hsv.into();
    println!("RGB: {:?}", rgb);
}
```

prints the following:

```
HSV: Hsv { hue: RgbHue(284.0), saturation: 1.0, value: 0.5, space: PhantomData }
RGB: Rgb { red: 0.5, green: -0.0000036358833, blue: 0.0, standard: PhantomData }
```

Note the negative value for the green component.

This is using the `arm-unknown-linux-gnueabi` target architecture. I will provide a more self-contained script to reproduce, but if anyone has any ideas on why this would be happening, feel free to comment. Thanks!

**Comment by Veykril** [comment] 2018-06-28 09:07
This is due to the Into/From implementation ignoring color space bounds currently, so these conversion are all unclamped which means that converting from a bigger garmut to a smaller one will result in invalid colors. If you are using the current github version you can make use of the ConvertFrom/ConvertInto traits, on the crates.io releases you will have to use the [clamp_self](https://ogeon.github.io/docs/palette/master/palette/trait.Limited.html#tymethod.clamp_self) method to fix the incorrect values for now.

**Comment by Ogeon** [comment] 2018-06-28 16:46
Yes, that's part lack of clamping and part floating point error, i think, but thanks for reporting! Clamping will be the default in the next release, and I have started working on a new set of conversion traits that should work better with that default.

I'm closing it as a duplicate of #41, but feel free to open it again if you think it's not just float inaccuracy. You can, for example, try with `f64` to see what happens with more precision.

**Closed** 2018-06-28 16:57 UTC
Labels: duplicate

**Comment by tiziano88** [comment] 2018-06-29 08:01
Thanks both, that is helpful! I am trying to get to the bottom of it but something even more mysterious is happening now:

```rust
fn print_color() {
    let hsv = palette::Hsv::new(palette::RgbHue::<f32>::from_degrees(284.0), 1.0, 0.5);
    println!("HSV: {:?}", hsv);
    let mut rgb: palette::rgb::LinSrgb = hsv.into();
    rgb.clamp_self();
    println!("RGB: {:?}", rgb);
}

fn main() {
    print_color();
    print_color();
}
```

prints the following:

```
HSV: Hsv { hue: RgbHue(284.0), saturation: 1.0, value: 0.5, space: PhantomData }
RGB: Rgb { red: 0.5, green: 0.0, blue: 0.0, standard: PhantomData }
HSV: Hsv { hue: RgbHue(284.0), saturation: 1.0, value: 0.5, space: PhantomData }
RGB: Rgb { red: 0.5, green: NaN, blue: 0.0, standard: PhantomData }
```

Note I am calling the same exact function twice, but the results are different, and there is no shared state between them. What is going on here?

**Comment by Ogeon** [comment] 2018-06-29 18:47
The implementation of clamp is

```rust
fn clamp<T: PartialOrd>(v: T, min: T, max: T) -> T {
    if v < min {
        min
    } else if v > max {
        max
    } else {
        v
    }
}
```

for each component, so unless there wasn't a `NaN` in there before, there shouldn't be a `NaN` after. Can you reproduce it with a print of the raw RGB value, before clamping, as well? If the HSV -> RGB conversion produces `NaN`, there may be an error or edge case in the conversion code.

**Comment by tiziano88** [comment] 2018-07-02 11:20
ah, found this which may be potentially relevant, will try building gcc from sources so that I can then use the *hf version to see if it helps: https://github.com/rust-lang/rust/issues/38570#issuecomment-268988110

**Comment by Ogeon** [comment] 2018-07-02 12:42
Alright, keep us posted in case it could be an issue in both ends.

**Comment by tiziano88** [comment] 2018-07-03 21:12
After a long investigation, and not finding anything related to how to properly cross compile Rust programs for Raspberry Pi 1 with FP support, I have written my own guide (in form of a Docker file: https://github.com/tiziano88/rust-raspberry-pi/blob/master/Dockerfile), and using that target for my program solved my issues; it seems that indeed the non-hf target has some bugs that caused the inconsistencies I was seeing, though I did not manage to get to the bottom of that.

**Comment by Ogeon** [comment] 2018-07-03 22:28
Let's hope that was it, then. :slightly_smiling_face: I can imagine the soft float implementation being slightly different, but I still don't understand why you would get different results from the same function call. Maybe it got optimized in some weird way...
