### ISSUE TITLE
Conversion from Lch to Rgb is broken, gives negative RGB values

### ISSUE THREAD

**Issue by ccfb3ee765a58cae** [Ogeon/palette#105] opened 2018-06-02 21:26 UTC
```rust
use palette::{LabHue, Lch, Rgb, FromColor};
let color = Lch::new(50.0, 100.0, LabHue::from_degrees(-175.78125));
let color: Srgb = Rgb::from_lch(color);
println!("{:?}", color);
// Rgb { red: -3.209118, green: 0.59184796, blue: 0.5073949, standard: PhantomData }
```

Should be rgb(1.0, 0.0, 0.43)

**Comment by Veykril** [comment] 2018-06-02 22:00
If I am not mistaken the result should be rgb(0.0, 0.59184796, blue: 0.5073949) but because lch has a wider gamut than rgb the red part goes out of the valid range. See #41

**Comment by Ogeon** [comment] 2018-06-03 09:34
Yep, [Lab and Lch have a wider gamut](https://commons.wikimedia.org/w/index.php?title=File%3ASRGB_gamut_within_CIELAB_color_space_mesh.webm), as @Veykril said, so there's always a risk of strange values in the outer parts, where the maths breaks down. I compared with the output of http://www.colormine.org/convert/lch-to-rgb and it looks like it gives the same result, but clamped to red = 0.0. You can use the [`Limited`](https://ogeon.github.io/docs/palette/master/palette/trait.Limited.html) trait to do the same until #41 is implemented.

**Comment by ccfb3ee765a58cae** [comment] 2018-06-03 18:51
Am I not using colormine.org's converter correctly? I keep getting rgb(1.0, 0.0, 0.43)

**Comment by Ogeon** [comment] 2018-06-03 19:55
Are you entering the hue with decimals? I think it only supports integers. I converted it to a positive integer value when I checked (`(360 + hue) % 360`), just to be sure.

**Comment by Ogeon** [comment] 2018-06-09 11:28
I'm closing this as a duplicate of #41, since I'm pretty sure it's just clamping that's missing, but feel free to reopen if you still think it's a different problem.

I was going to refer to the test suite as "evidence", but it seems like there are missing tests for conversion from `Lch` and `Lab` to other spaces, so that fell flat. The problem we had with them should however be fixed now, so I'll create an issue for adding them.

**Closed by Ogeon** 2018-06-09 11:28 UTC
Labels: duplicate
